"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cls } from "../libs/utils";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import HeaderTabBar from "@/components/header-tap";
import BottomTabBar from "@/components/bottom-tap";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayout {
  main?: boolean;
  children: React.ReactNode;
  title?: string;
  canGoBack?: boolean;
  hasTabBar?: boolean;
}

export default function RootLayout({
  main,
  children,
  title,
  canGoBack,
  hasTabBar,
}: RootLayout) {
  const router = useRouter();
  return (
    <html lang="en">
      <body
        className={cls(
          "w-full max-w-xl mx-auto pt-[80px]",
          inter.className,
          title ? " pb-[70px]" : ""
        )}
      >
        {!main ? (
          <HeaderTabBar canGoBack={canGoBack}>
            {canGoBack ? (
              <button onClick={() => router.back()}>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  className="w-6 h-6"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M15.75 19.5L8.25 12l7.5-7.5"
                  />
                </svg>
              </button>
            ) : null}
            {title ? <span>{title}</span> : null}
          </HeaderTabBar>
        ) : null}
        {children}
        {hasTabBar ? <BottomTabBar /> : null}
      </body>
    </html>
  );
}
